export enum Status {
  PENDENTE = 'PENDENTE',
  CADASTRO = 'CADASTRO',
  DESCRICAO = 'DESCRICAO',
  IMAGENS = 'IMAGENS',
  PROCODE = 'PROCODE',
  CONFERENCIA = 'CONFERENCIA',
  CONCLUIDO = 'CONCLUIDO',
  ERRO = 'ERRO',
}
